# Generated by Django 2.1.5 on 2020-01-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=50)),
                ('lastName', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phoneNumber', models.TextField(blank=True, max_length=50)),
                ('birthday', models.DateField()),
                ('subject', models.CharField(blank=True, choices=[('Subject 1', 'Subject 1'), ('Subject 2', 'Subject 2'), ('Subject 3', 'Subject 3')], max_length=20)),
                ('is_male', models.BooleanField(default=False, verbose_name='IS Male')),
                ('is_female', models.BooleanField(default=False, verbose_name='IS Female')),
            ],
        ),
    ]
